### ISSUE TITLE
Crafting labels mixed up.

### ISSUE THREAD

**Issue by Dirk-Dieters** [ibm2431/recipe-sql-viewer#1]
Cooking recepies listed as woodworking
Alchemy listed as smithing
leatherworking listed as goldsmithing
Goldsmithing listed as clothcraft
Bonecraft recipes listed as leathercraft
Smithing listed as bonecraft
Woodworking listed as Alchemy
Clothcraft listed as cooking

**Comment by ibm2431** [comment]
Hit "New Recipe Order" when you load~

**Comment by Dirk-Dieters** [comment]
Ah, I see, have to have that checked before loading. Gotcha
